### ISSUE TITLE
make Shl Shr 64bit operators

### ISSUE THREAD

**Issue by meemoeuk2** [bmx-ng/bmx-ng#130]
In BM-NG bcc[ng], 0.129, bmk 3.45 mt-win32-64 gcc 080100 (cpu x4) GCC version 8.1.0 G++ version 8.1.0

Local a:Long = 1 Shl 32
Print a

expected output : 2147483648
actual output      : 1

Shl Shr are only 32bit operators. please overload Shl, Shr and all other bit operators so they can do 64bit operations.

Usage : my code packs and unpacks Longs with a lot of data. such as bitflags, co-ordinates, directions, indices etc. Shl Shr are useful in this packing | unpacking process.

**Comment by GWRon** [comment]
```
SuperStrict
Framework Brl.StandardIO

Print "expected: 2147483648"

Local a:Long = 1 Shl 32
Print "int shl 32 = " + a

a = 1:Long Shl 32
Print "long shl 32 = " + a
```

output
```
expected: 2147483648
int shl 32 = 1
long shl 32 = 4294967296
```

when not stating what "number type" (byte, int, short, long, double ...) to use for your constant value "1" it defaults to "integer". Which is in Blitzmax an unsigned integer with the size of 32bit (so shifting by 32 leads to ...1)

**Comment by meemoeuk2** [comment]
i see. ok i can work with that protocol in my code. Though I think its a little counter-intuitive. If the LHS is defined as a particular number type, then I'd expect the compiler would assume the RHS numbers to be of the same type rather than default to Int.

**Comment by HurryStarfish** [comment]
Note that there are still some issues with the type suffixes in BlitzMax-NG (see https://github.com/bmx-ng/bcc/issues/277) - so be careful with those. If you wanna be safe, store the numbers in variables first.

**Comment by GWRon** [comment]
Yes ... expectactions and assumptions lead to bugs in my code too --- here and then.

this is why NG also warns if you pass certain number types as param to functions expecting number types with lower "range" (potential loss). So `func(a:int)` blames if you pass "a:long" to it, but does not warn you when passing "a:byte".

Also potential issues are when using "sin()" or "cos()" - they return doubles. So `local sinValue:Float = sin(angle)` would lead to a warning (or an error, if set so compiler options).

Another thing to consider are floats. So `local d:double = 1.234567` would assign a float (which might have already lost some bits of precision - not sure about it as the code generation might circumvent it, so see it as exaggeration). So better write `local d:double = 1.234567:double`

**Comment by HurryStarfish** [comment]
> Though I think its a little counter-intuitive. If the LHS is defined as a particular number type, then I'd expect the compiler would assume the RHS numbers to be of the same type rather than default to Int.

This would break bakwards compatibility with existing code. But even if it didn't, it would be problematic for a couple of reasons:
It would require that expressions are no longer evaluated "inside-out": the meaning of a literal such as `1` would change depending on where it is used. Not only would that be counter-intuitive to anyone who has used a different programming language before, it would also be very difficult to implement and could get confusing in anything but the most trivial cases. For example, what should the following print?
```
Local i:UInt = -3 + 0.5
Print i
```
This currently gives you `4294967294`, the result of converting `-2.5` to `UInt`.
If the compiler were to convert the `-3` on the RHS to `UInt` because of the LHS , you'd suddenly get `0` instead; if it converted both `-3` and `0.5`, you'd get `4294967293`.
Any of these three results might be surprising to a programmer who expected things to work differently, but the current behaviour (calculate `-3 + 0.5` first, then do whatever with the result) is the easiest to follow for both the programmer and compiler.s

**Comment by DruggedBunny** [comment]
> So `local d:double = 1.234567` would assign a float

Oh! That's interesting... never occurred to me before!
