### ISSUE TITLE
blitzmax is deprecated on ubuntu 22.04, i could not successfully compile modules

### ISSUE THREAD

**Issue by zarosath** [bmx-ng/bmx-ng#149]
**Describe the bug**

/home/william/Desktop/BlitzMax/mod/brl.mod/platform.mod/glue.c:24:10: fatal error: sys/sysctl.h: No such file or directory
   24 | #include <sys/sysctl.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.

**Version information (please complete the following information):**
 - OS: ubuntu 22.04/ubuntu 18.04
 - [BlitzMax Linux.x64 v0.133.3.48](https://github.com/bmx-ng/bmx-ng/releases/tag/v0.133.3.48.linux.x64)

**Additional context**
[Add any other context about the problem here.](https://askubuntu.com/questions/1082722/unable-to-locate-package-libesd0-dev-on-ubuntu-18-04)

From Ubuntu 18.04 libesd0-dev is deprecated. For this you need to add repositories of xenial, i.e. repository of a previous Ubuntu release which is still supported, in sources.list

Thank you for your support.

**Comment by GWRon** [comment]
As I have written to you on discord:

I cannot replicate that issue on a fresh installed 22.04. @scaremonger was also not able to replicate that issue.

The line you reported should only be included on Mac OS...

This is why I asked what a simple sample spits out for you:

```Blitzmax
SuperStrict
Framework Brl.StandardIO
?MacOS
print "I am on a Mac"
?not MacOS
print "I am NOT on a Mac"
?
```
> What does it print for you?


But you now already installed 18.04 and are not able to try it out.
Means you cannnot help to narrow down that potential bug.
Others cannot replicate it...and you can't help now too. Think this is not optimal.



Regarding libesd ..think that issue is raised somewhere already. It just should be removed from the sources ...it will work for 99% of the users without support of this backend.

**Comment by zarosath** [comment]
i tried using virtualbox with the 22.04 iso from windows (for some reason it was in the recycle bin), it failed to boot the iso. i will be trying.
