### ISSUE TITLE
Different Compile error on Windows and Mac with Same app

### ISSUE THREAD

**Issue by sphinxeg** [bmx-ng/bmx-ng#21]
I am have a game which I wrote along time ago using the old BB, Converted it to BlitzMax with the help of a wrapper for old BB functions names.

When I use Mark's or Skid's BlitzMax build, it compiles and works with no problem, but when I use NG v0.87.3.16 (Windows 7 32bit) it gives an error saying 'Compiler Error : Unable to convert Object to Int'.

I tried NG on MacOS Sierra 10.12.6 and it gives a completely different error this time saying 'identifier 'KEY_ALT' not found'!, though it works with no problem with Mark's and Skid's build!

Any clue?!

**Comment by GWRon** [comment]
As written on syntaxbomb (I am just a guest-reader :-)) already the issue is you are not using at least `strict` for your code.

So ALT_KEY is an undefined ("never used before") variable which often is "0" but might even be a random-memory-garbage-thing (if there is no "initialization value given" by the language/module).


With int/object: in vanilla-non-strict you are able to return an object as int, so this worked there - but now you should do differently.


As the issue is "solved" I suggest to close it.

**Comment by woollybah** [comment]
Hallo :-)

```KEY_ALT``` is not a valid keycode in BlitzMax. According to BRL.Keycodes/keycodes.bmx, the ALT key consts are :
* Const KEY_LALT=164
* Const KEY_RALT=165

In the old/legacy/vanilla BlitzMax, when you don't specify a strictness (of either Strict or SuperStrict), the default is for all variables to be of the type Int. So, a variable for holding an Object is an Int variable until you try to put an Object into it.
All of this is fine, until you find yourself with a bug that for the life of you, you cannot work out where the problem is - eventually, it turns out to be that one of your variables which you had been using to store a number in it, was mistakenly set as an Object elsewhere, and when you came to increment the value, your program crashed.
Strict (and more so SuperStrict) prevents you from making silly errors like this, by requiring you to be more precise and specific as to the type of your variables. It also doesn't magically allow you to create new variables/consts on-the-fly like your ALT_KEY variable, therefore potentially preventing other errors in your program where you are assuming that you are testing for a certain key, when in fact you are not.

I would recommend you migrate your code to (at least) Strict, even if the task appears to be somewhat daunting - it's likely that you will end up fixing a load of bugs in your program that you didn't even know were there.

"Int for everything" may have seemed like a wonderful idea for someone, once. But these days, when your pointers are 8-bytes big (on 64-bit OS) and not 4-bytes (32-bit OS), assuming everything is only 4-bytes big is not going to get you very far. Since NG is also targeting 64-bit architectures (on desktop and mobile) it needs to be *much more* strict, and hence why some parts of BlitzMax in NG now use Byte Ptr instead of Int to store information - an Int is not big enough for all data.

**Comment by sphinxeg** [comment]
Thank you very much guys for your reply :)
