### ISSUE TITLE
Long compilation times when incbinning big files

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmx-ng#31]
Wanted to write that in my reply within the incbin-EAV-issue but it might be better to have its own issue:

 
When incbinning a big file (the 9MB fontmachine-fmt-file of the EAV issue #29 ) it takes "ages" here (side note: without _framework_ command.
So when compiling without the incbin I get (on my test notebook) a compilation time:
~1 sec for __processing__ incbin.bmx
~3 sec for __compiling__ incbin.bmx
-> 4 seconds in total (including linking to an .exe)

Compiling with incbinning the file leads to:
~8 sec for __processing__ incbin.bmx
~36 sec for __compiling__ incbin.bmx
-> 44 seconds in total (including linking to an .exe)

the "incbin.bmx.release.win32.x86.incbin.h" file is 44.587 KB big ... which is surely the reason for a that huge compilation-time (and "processing" is then doing the "translation from binary data to .h-string").

Is there a way to do it so that the compiler does not need to parse it each time? Like adding a new ".o" file instead? Caches are not that simply to add as file contents need to be matched (you would need to check file hashes or so - which could take some time too). So the new way might still need to process the incbinned file each time - with the difference to now just being the skipped "compilation" (.h file).

**Comment by GWRon** [comment]
Hmmm might GCC's `objcopy` be of use there? 
It generates an .o-file for the attached binary which can be linked then easily. Dunno if that is faster (when done "live" on each compilation call) than processing the binary into a string hash which gets compiled then:

https://balau82.wordpress.com/2012/02/19/linking-a-binary-blob-with-gcc/

**Comment by HurryStarfish** [comment]
`IncBin`ing huge files should probably be avoided in general. Then again, 9MB isn't quite what I'd call "huge" yet. For the time being, as long as the file doesn't change, you can at least move the `IncBin` into a separately imported file so it doesn't have to recompiled everytime you change something in your code.

**Comment by davecamp** [comment]
For stats ( with the Framework command are practically the same as without Framework command )...

When incbin-ing 9MB file I get
~1 sec for bcc to process and create the .h file.
~20 sec for gcc/cc1 to process it and build an exe.

When not incbinning I get
~1 sec for the whole compilation process to build, create and get the exe running.

Build times will be 
This kind of loops back to a suggestion I made about bmk checking .o file stamps against .c ( and also for this situation: .h ) source files to check whether or not a file has been modified - then decide whether gcc should compile the source or not.

**Comment by woollybah** [comment]
The latest commits for bmk and bcc now put incbin'd files into their own object file (.o).
This should remove the issue where compiling a .bmx with incbin'd files could take some time to compile the generated .c for large files - because the included incbin header needed to be compiled by gcc each time.

It should now be the case that the incbin'd .c source is only (re)generated when its contents change, and the object file recompiled when the source is updated. Otherwise, it will usually only be linking the object file and not compiling it.

Once you have the new bmk and bcc installed, you shouldn't need to rebuild as bmk should determine any instances of incbins and rebuild those as required.

I'll leave this open for a while in case there are issues with it. Feel free to report your results either way. Thanks!
