### ISSUE TITLE
Bmx-NG release g++ error

### ISSUE THREAD

**Issue by HenriVi** [bmx-ng/bmx-ng#33]
Hi Brucey,

I downloaded the new release (Windows), and trying to compile Print "Hello" without any pre-building of modules, I get this when executing:

g++.exe: error: unrecognized command line option '--stack=4194304'
g++.exe: error: unrecognized command line option '--subsystem,windows'; did you mean '--machine-windows'?
g++.exe: error: unrecognized command line option '-mthread'; did you mean '-mthreads'?
Build Error: Failed to link C:/BmxNG_new/tmp/untitled1.debug.exe

-Henri

**Comment by woollybah** [comment]
Which is interesting, because I did a hello world test and a build of maxide before release - yes, I know that's not much of a test...

**Comment by woollybah** [comment]
Is that the x86+x64 release?

**Comment by HenriVi** [comment]
Well, it is working fine on my home setup. Guess there is something special about my working environment.

-Henri

**Comment by DruggedBunny** [comment]
For what it's worth, the x86 + x64 setup is what I'm using and it's working here at least.

I don't have an installed MINGW path myself, wondered if that might be the problem, ie. it's using another version?

Does g++ or gcc run from command line show anything? Unless I cd into one of the bmxng-supplied MinGW\bin folders I get "'g++' is not recognized as an internal or external command ...".

If it is recognised, try calling "where g++" or "set MINGW" to try and get the path being used.

**Comment by HenriVi** [comment]
The mixing of files is the logical explanation, although it is curious as to how that can be. I did some playing   
with the environment variable, but to no obvious conclusion. For the time being I'll give it a rest. It is nothing critical it seems.

**Comment by GWRon** [comment]
Are you using symlinks (or mapped folders...)?
Bmk (or more exact the helper functions in brl.mod) have issues when you use symlinked folders.

**Comment by DruggedBunny** [comment]
Interesting, what exactly is it that fails with symlinked folders (assuming Windows-specific)?

Made me think of this PureBasic code I made to skip recursive parsing of symlinked folders -- GetFileAttributes and FILE_ATTRIBUTE_REPARSE_POINT being from the Win32 API. If **zero** then the folder's **not** symlinked/junctioned and can be safely parsed:

```
attr = GetFileAttributes_ (@folder$)

If attr & #FILE_ATTRIBUTE_REPARSE_POINT = 0
	ParseFolder (folder$, count + 1)
EndIf

```
Without this, it caused infinite recursion.

Might be what's needed to resolve... whatever it is!

**Comment by GWRon** [comment]
Cannot say things about Windows - had this issue on Linux:
I had a BlitzMaxNG folder, containing a normal folder for the mods. But "brl.mod" and "pub.mod" were symlinks to something like "projects/bla/bla/brl.mod.git" and ".../pub.mod.git". So I had all git projects at a central place but kept "BlitzMaxNG" in a tools folder.
I also tried to symlink binaries (bmk from "...bla/bmk.git") and at the end it reported some issues about files not found.
This was because ... if i remember correctly ... BMK/BCC handle stuff with "relative paths" (so "../mods/brl.mod" instead of "/path/to/blitzmax/mods/brl.mod") and the fact that it resolved symlinks automatically. Am not sure and will have to check when at home on my computer (and having some more spare time).

**Comment by GWRon** [comment]
Still valid or some solutions to post? Else ... close?
