### ISSUE TITLE
[makemd] Handle "extra" examples

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bmx-ng#44]
Where we have extra examples for a given function, the filename will have a trailing "_X", where X is a number starting from 1.

These examples should also be added to the documentation.

**Comment by woollybah** [comment]
In addition, examples of overloaded methods should be supported.
Currently, an example with the method name will be applied to all overloaded methods - which is incorrect, as the arguments are not the same.
`makemd` is already generating a `proto id` for each method, and I think we should also use that to determine if an example belongs to a particular method.
The example filename will need to reflect exactly whatever proto the method defines. Maybe we should add an option for makemd to output the protos for methods so we know what they are when we want to name the file.
Perhaps something along the lines of
`Type : Method : proto`

**Comment by GWRon** [comment]
Couldn't it use the "mangled" naming scheme BCC already uses?
MyFunc:int(i:int,f:floaT) => myfunc_i_f
or so?
This would make it predictable too - no need to output additional stuff.

**Comment by woollybah** [comment]
Well, rather than work stuff out for myself or dig through generated sources, I thought it would be easier to add an option to makemd to produce output as it processed the files, which I could then refer to :-)
Anything that requires me not to have to think, is a :+1:

**Comment by HurryStarfish** [comment]
I'd imagine the lazy way would be to have the bbdocs directly link to the example, rather than trying to make the connection through the file name.
Compared to now, that would have the disadvantage that you'd need to change the source to add or remove an example, but also the advantage that it's harder to forget to adjust the example if you ever change the function/method signature.
