### ISSUE TITLE
Function calls in params are evaluated right-to-left.

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmx-ng#54]
```BlitzMax
SuperStrict
Framework Brl.StandardIO

Function test:Int(p:Int)
	Print p
	Return p
End Function


Function twoTests:Int(p1:Int, p2:Int)
	Print "twoTests: " + p1+" " + p2
End Function

twoTests(test(1), test(2))
```

```
Executing:untitled1.debug
2
1
twoTests: 1 2
```

This is interesting as eg. the "TMapXMLSerializer" of TPersist.mod does this:
```
map.Insert(DeserializeObject(keyNode), DeserializeObject(valueNode))
```
and if the valueNode contains a reference to keyNode it tries to get mapped before the key got deserialized.

In my opinion functions need to get called "left to right".

**Comment by HurryStarfish** [comment]
According to a quick test, arguments seem to get evaluated from right to left in vanilla too. But this might be coincidence; I don't know whether parameter evaluation order is actually defined in vanilla. It doesn't seem to be defined in NG right now: that call `twoTests(test(1), test(2))` translates to `_m_untitled49_twoTests(_m_untitled49_test(1),_m_untitled49_test(2));` and afaik, in C the order of evaluation of the parameters is undefined. 
If we had a defined evaluation order, I agree that left-to-right would make most sense.

That said, using side-effect-causing function calls as part of expressions is generally considered bad practice, since it can quite easily cause confusion and bugs and should thus be avoided when possible (in any language, not just BlitzMax). But for now, you can force a specific order for the function calls by storing the intermediate values in local variables first:
```
Local t1:Int = test(1)
Local t2:Int = test(2)
twoTests(t1, t2)
```

**Comment by GWRon** [comment]
Yes I already used this approach to circumvent the issue.

I never used multiple (depending on each other) functions in my code so I was not aware of it - it just happened when using Bruceys revamped TPersistence.mod  - which did above when handling a TMap. Seems the mighty fail sometimes too. Only a human - hah!

**Comment by woollybah** [comment]
I will add a note to the documentation about execution order of function arguments.
