### ISSUE TITLE
Imports type

### ISSUE THREAD

**Issue by llYuell** [bmx-ng/bmx-ng#62]
With one import I don't have access to other types of data.

`'File Main
Import "TG3D.bmx"

' File TG3D

Type TG3D
     field Draw:TDraw 'Error no exists TDraw

End Type 
`

Is there a way to access another type, or is it simply not possible?

**Comment by woollybah** [comment]
To access `TDraw` you'd need to import the file that contains it. If that file is `Main`, you should move it to another file, so that other files may import it.

For example.
```blitzmax
`'File Main
Import "TG3D.bmx"

' File TG3D
Import "draw.bmx"

Type TG3D
field Draw:TDraw 'Error no exists TDraw

End Type

' File draw.bmx

Type TDraw
End Type
```

**Comment by HurryStarfish** [comment]
Note that your `TG3D` file does not need to import the exact file `TDraw` is defined in. Indirect imports are fine too, e.g. `TG3D` imports another file (which imports another file...) which imports `TDraw`.

What you can *not* do is create circular imports (two files directly or indirectly importing each other). If you run into that problem, it's usually a good idea to rethink the structure of your program - there often is a better way to arrange things that solves the problem. Alternatively you can use `Include` instead of `Import`, but keep in mind that like in C/C++, `Include` simply pastes the contents of one file into the other and thus doesn't give you the encapsulation benefits `Import` has.

**Comment by llYuell** [comment]
Well, going deeper into this subject I found the most president formula to work.

I have the following classes/types.
TApp
TG3D

The TApp class is called with the Import command, but within the TApp case I use an include to call TG3D.

In that case from TApp it is possible to access TG3D.

Include "TG3D.bmx"
Type TApp

Private
field G3D:TApp

end type

But TApp serves to make those classes private, but from TApp, I have access to all members of all classes as TG3D, but the only one that I intend to expose to the end user is the TApp class and this give entry or not to different classes, suc

Translated with www.DeepL.com/Translator
