### ISSUE TITLE
How to check an array for "null" (NO initialization)?

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmx-ng#97]
```BlitzMax
SuperStrict
Framework Brl.StandardIO

Function FetchResults:Object[]()
	Local res:Object[]
	'do some DB lookups
	'tick tack tick tack
	'res = mydb_fetch_array(myquery)
	res = New Object[0] 'an existing array with ZERO entries
	Return res
End Function

Local resultsNULL:Object[] = Null
'nope, does not exist
If Object(resultsNULL) Then Print "NULL array exists as object"

Local results:Object[] = FetchResults()
'nope, does not exist
If Object(results) Then Print "0-entries array exists as object"


If results = Null 
	Print "array is NULL"
	Print "but this NULL array has a length and can add stuff ..."
	Print results.length
	results :+ [Object("string")]
	Print results.length
Else
	Print "array length: " + results.length
EndIf
```

In this example: how to distinguish an "empty result set" from "fetch command not yet run" ? So in other words: If I initialized an array with "Null" I can still add something to it - even if the object is Null.
So how to find out if something created an array but ... a one with 0 entries? Would prefer to avoid another variable returning the amount of "hits" or a "true/false" for success/having created the result.

Edit: Run the above in vanilla and the two "exists"-prints are executed. In NG (latest BCC of today) this is not printed. This is interesting as the "null"-array should not exist at all (in my opinion) while the "empty array" should.

**Comment by woollybah** [comment]
The previous version of bcc should return the same results as vanilla.
The difference is what happens when an Object is tested against Null. The specific test compares the instance against `&bbNullObject`. But this is only true for actual Objects, and not Arrays or Strings.
My change modifies the Object/Null test to also take `&bbEmptyArray` and `&bbEmptyString` into account to. A "null" array and an empty array are the same, as far as BlitzMax is currently concerned. As is a "null" string and an empty string.

**Comment by GWRon** [comment]
So it does this in the way it does for `if 0:int = null` and `if "" = null` ?
Is there a way to add a function checking the underlaying "c-variable" if it was "nil" or so?

Or how to achieve the desired ability to distinguish between an "empty array" and a "not initialized array" (so "empty resultset" versus "not yet tried to fetch any result").
Is this even possible or am I forced to have a boolean ("fetchedResults:int = true") to check in addition?

I think I am using this "= null" checks sometimes in my game - to see if I already build a "result cache" knowing this now I can see it doing a "result scan" more times than needed (as even a filtered result array with 0 elements is recognized as "not yet caches, recreate cache").

**Comment by GWRon** [comment]
BTW: Doesn't that mean the initialization of an array with `arr =new MyType[0]` is the same as writing `arr = null` ? It somehow sounds .. "wrong".

**Comment by woollybah** [comment]
Indeed. This is how it's always been though... :-)

**Comment by GWRon** [comment]
Hmmm. Ok.

**Comment by woollybah** [comment]
That's not to say we can't make changes at some point that would allow us to differentiate between a Null array and an empty array.

I made the recent changes primarily because my unit tests (yes :-p ) for jconv had raised an issue with the way I wanted to handle a "null" array, having access to it via an Object. Basically the Object would never be Null in this situation, which wasn't useful in my particular use-case.

**Comment by GWRon** [comment]
I think the "real null" could be added once stuff like "strings" or "numbers" become objects (as proposed by @HurryStarfish some months ago). Which is guaranteed to break any backwards compatibility (so make sure basic stuff is working flawless so there is no need to compile with legacy here and there to avoid potential NG bugs ;-)).


For now I think I will (have to) come along with this and it worked that way in vanilla so for now I am fine with that "issue".
