### ISSUE TITLE
Question: Passing methods as function params.

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmx-ng#99]
For now my event manager allows to pass functions as params (callbacks). When I want to pass in a method I for now do it by passing the object and the method name as string: `**EventManager.registerListenerMethod("ProgrammeLicence.onGiveBackToLicencePool", self, "onGiveBackLicenceToPool")`. Means I need to rely on "reflection" to find the method each time (or cache it in a `field meth:TMethod` then.

Is there a way for NG to allow passing a "TMethod" (not calling it that way - as it is a brl.reflection thing)?

**Comment by HurryStarfish** [comment]
Unfortunately not, no. At least not currently.
Since methods have the object they're called on as a "hidden parameter" and can be overridden, they work a bit differently than functions behind the scenes.
You have to either use reflection, or write a wrapper function for each of these methods and then pass those to your manager instead. With lambda expressions/closures, this will be easier.

**Comment by GWRon** [comment]
Thanks for your fast reply. Thought about that wrappers too... But it pollutes sources... Lets better wait for lambda expressions :-)
